### PR TITLE
Replaces msvc only string functions with standard ones.

### PR DESCRIPTION
**Pull request by OmniBlade**
Several changes to fix code or swap windows only functions for C++ standard equivalents to allow building on Linux.

### CODE REVIEW

**Comment by arves100** [comment]
Hello, thanks for your work. I am aware of the Linux string functioms that
were MSVC specific. However, this breaks the secure functions with msvc
(that i pushed to use). I will perform a commit on MDK that will allow to
define this function for Linux.
While on some part, using ifdefs
(Example: #define strcpy_s(out, outsize,in) strcpy(out, in) ).

Il dom 26 ago 2018, 00:35 OmniBlade <notifications@github.com> ha scritto:

**Comment by OmniBlade** [comment]
Strcpy isn't secure as you can get buffer overruns, strncpy will only write the number of bytes specified and the extra null termination ensures it is properly terminated. I don't really see what extra strcpy_s gets you since you don't check it's returns to check for truncation or anything.

I guess you could ifdef to get effectively the same functionality across different platforms though.

**Comment by arves100** [comment]
That's a point, The secure does not write if the buffer is smaller enought,
but I don't check that. I guess it could be merged with strncpy after all
and defining the _CRT_SECURE_NO_WARNING. (Since there is also strncpy_s).

Il dom 26 ago 2018, 08:52 OmniBlade <notifications@github.com> ha scritto:

**Comment by arves100** [comment]
I will merge the commit, should also be easier to read rather than using _s function. I could change them later if needed with some ifdefs.

**Pull request merged**
